### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by romevi** [venmos/w3m-layer#3]
The keybindings don't seem to add.

**Comment by venmos** [comment]
Im so sorry, this project is no longer under maintenance, I am no longer using Emacs.
Spacemacs may have made some minor modifications to the key bindings，it should be easy to fix.

**Comment by romevi** [comment]
Okay, thanks. I was able to figure out.
I don't think you need
```
(setq-default dotspacemacs-configuration-layers '(
                                                  w3m
))
```
in your .spacemacs. I tested it with and without and the keybindings worked fine.
