### ISSUE TITLE
how to configure a proxy 

### ISSUE THREAD

**Issue by AlanWZHU** [venmos/w3m-layer#5]
Hi,I have successfully loaded this layer ,but I can not find a proxy configuration , 大神，可以增加一下配置添加代理的部分么，我刚从vim转到spacemacs，对elisp 不熟

**Comment by venmos** [comment]
This can be done in your ~/.emacs-w3m.el file as shown below:

```lisp
 (setq w3m-command-arguments
       (nconc w3m-command-arguments
              '("-o" "http_proxy=http://proxy.hogege.com:8000/")))
```
